# Lesson_3_Матрицы_и_матричные_операции,_Часть_1

### 1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .

Решение произведения определены только для матриц в) АВ -8*8 и г) АВ - 4*4 

    
### __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

Решение:

$A+B=\begin{pmatrix}
(1+4) & (-2-1)\\ 
(3+0) & (0+5)
\end{pmatrix}= \begin{pmatrix}5 & -3\\3&5\end{pmatrix}$

$A*B=\begin{pmatrix}
(1*4+(-2*0)) & (1*(-1)-2*5)\\ 
(3*4+0*0) & (0*5+3*(-1))
\end{pmatrix}= \begin{pmatrix}4 & -11\\12&-3\end{pmatrix}$

In [1]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'A+B \n {A + B}\n')
print(f'A*B \n {np.dot(A, B)}\n')

A+B 
 [[ 5 -3]
 [ 3  5]]

A*B 
 [[  4 -11]
 [ 12  -3]]



### __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

Решение:

$3A =\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$, $2B=\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$, $4C=\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}.$

$3A-2B+4C =\begin{pmatrix}
(3-0+8) & (21-10-16)\\ 
(9-4+4) & (-18+2+4)
\end{pmatrix}=\begin{pmatrix}11&-5\\9&-12\end{pmatrix}$

In [5]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'3A-2B+4C \n{3*A-2*B+4*C}')

3A-2B+4C 
[[ 11  -5]
 [  9 -12]]


### __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

Решение:

$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$A*A^T=\begin{pmatrix}
(4*4+1*1) & (4*5+1*(-2)) & (4*2+1*3)\\ 
(5*4+(-2)*1) & (5*5+(-2)*(-2)) & (5*2+(-2)*3)\\
(2*4+3*1) & (2*5-3*2) & (2*2+3*3)
\end{pmatrix}= \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$.

$A^T*A=\begin{pmatrix}
(4*4+5*5+2*2) & (4*1-5*2+2*3)\\ 
(1*4-2*5+3*2) & (1*1+2*2+3*3)
\end{pmatrix}= \begin{pmatrix}
44 & 0\\ 
0 & 14
\end{pmatrix}$.

In [2]:
A = np.array([[4, 1],[5, -2],[2, 3]])
print(f'A^T \n {A.T}\n')
print(f'A*A^T \n {np.dot(A, A.T)}\n')
print(f'A^T*A \n {np.dot(A.T, A)}\n')

A^T 
 [[ 4  5  2]
 [ 1 -2  3]]

A*A^T 
 [[17 18 11]
 [18 29  4]
 [11  4 13]]

A^T*A 
 [[45  0]
 [ 0 14]]



### __5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [10]:
def funk(a,b):
    rezult = []
    for k in range(len(a)):
        rez_str = []
        for j in range(len(b[0])):
            s = 0
            for i in range(len(a[0])):
                s = s + a[k][i]*b[i][j]
            rez_str.append(s)
        rezult.append(rez_str)
    return rezult
            

In [11]:
A = [[4,1],[5,-2],[2,3]]
B = [[4,5,2],[1,-2,3]]
print(funk(B,A))
print(funk(A,B))

[[45, 0], [0, 14]]
[[17, 18, 11], [18, 29, 4], [11, 4, 13]]


# Матрицы и матричные операции. Часть 2

### __1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

Решение:

a) sin(x)*sin(x) - cos(x)*cos(x) = sin(x)^2 - cos(x)^2 = -1

b) $4*\begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix} -
2*\begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix}+
3*\begin{vmatrix}
0 & 5\\ 
0 & 0
\end{vmatrix}=4*45-2*0+3*0 = 180
$

в) $1*\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix} -
2*\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix}+
3*\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix}=1*(45-48)-2*(36-42)+3*(32-35) = -3+12-9 =0
$

In [3]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
v = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'определитель матрици b \n{np.linalg.det(b)}\n')
print(f'определитель матрици в \n{np.linalg.det(v)}\n')

определитель матрици b 
180.0

определитель матрици в 
0.0



### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
   Решение:
   
   a) 16
   
   б) 4
   
   в) 8

### __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Решение:

найдем определитель матрицы

в) $-2*\begin{vmatrix}
-14 & 6\\ 
7 & 13
\end{vmatrix} -
7*\begin{vmatrix}
4 & 6\\ 
-3 & 13
\end{vmatrix}-
3*\begin{vmatrix}
4 & -14\\ 
-3 & 7
\end{vmatrix}=-2*(-224)-7*(70)-3*(-14) = 0
$

определитель равен 0, следовательно матрица не имеет обратной и являеться вырожденной


In [7]:
m = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'определитель матрици m \n{np.linalg.det(m)}\n')

определитель матрици m 
0.0



### __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Решение:

а) третья строка это сумма 1 и 2 поэтому ее можно отбросить. 1 и 2 строки линейно не завилимы поэтому ранг = 2

б) третья строка это сумма 1 и 2 поэтому ее можно отбросить. 1 и 2 и 4 строки линейно не завилимы поэтому ранг = 3

In [11]:
a = np.array([[1,2,3],[1,1,1],[2,3,4]])
b = np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
print(f'ранг а = {np.linalg.matrix_rank(a)}')
print(f'ранг b = {np.linalg.matrix_rank(b)}')

ранг а = 2
ранг b = 3
