### __1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

Решение: 

найдем собственные значения линейного оператора, составив и решив характеристическое уравнение

$\begin{pmatrix}
-1 - \lambda & -6\\ 
2 & 6 - \lambda
\end{pmatrix}=0$

$(-1-\lambda)*(6-\lambda)-2*(-6)=0$

$\lambda^{2}-5\lambda+6=0$

$\lambda_{1}=3, \lambda_{2}=2$

получаем 2 уровнения

$\textbf{A}x=\lambda_{1}x$

$\textbf{A}x=\lambda_{2}x$

подставим наши значения:

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
3
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
2
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$

при перемножении получаем

$\begin{cases}
-1x_{1}-6x_{2}= 3x_{1}, \\
 2x_{1}+6x_{2}= 3x_{2}.
\end{cases}$

$\begin{cases}
-1x_{1}-6x_{2}= 2x_{1}, \\
2x_{1}+6x_{2}= 2x_{2}.
\end{cases}$


в итоге получаем $x_{1}= \frac{-3x_{2}}{2}$ и $x_{1}= -2x_{2}$ где $x_{2}$свободные переменные кроме 

(-1.5,1),(-2,1)

In [1]:
import numpy as np
a = np.array([[-1,-6],[2,6]])
w,v = np.linalg.eig(a)
print(f'собственные знач \n{w}')
print(f'собственные векторы \n{v}')

собственные знач 
[2. 3.]
собственные векторы 
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


### __2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

Решение:

$\begin{pmatrix}
-1 - \lambda & 0\\ 
0 & -1 - \lambda
\end{pmatrix}=0$

$(-1-\lambda)^{2}=0$

$\lambda=-1$

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
a\\ 
b
\end{pmatrix}=
-
\begin{pmatrix}
a\\ 
b
\end{pmatrix}.
$

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix} = -1$



$\begin{cases}
-a = -a\\
-b = -b
\end{cases}$

In [2]:
a = np.array([[-1,0],[0,-1]])
w,v = np.linalg.eig(a)
print(f'собственные знач \n{w}')
print(f'собственные векторы \n{v}')

собственные знач 
[-1. -1.]
собственные векторы 
[[1. 0.]
 [0. 1.]]


### __3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

Решение:

$A=\begin{pmatrix}
1 - \lambda & 1\\ 
-1 & 3 - \lambda
\end{pmatrix}=0$

$(1-\lambda)(3-\lambda)+1=0$

$\lambda = \frac{4+-32^{0.5}}{2}$

собственное значение это комплексное число вектор (1,1) не являеться комплексным поэтому от не явсяеться собственным вектором оператора А

In [3]:
a = np.array([[1,1],[-1,3]])
w,v = np.linalg.eig(a)
print(f'собственные знач \n{w}')
print(f'собственные векторы \n{v}')

собственные знач 
[2.00000002 1.99999998]
собственные векторы 
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


### 4. Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

Решение: предположим что вектор х являеться собственным вектором оператора А

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\ 
0 & 0 & 3 
\end{pmatrix}
\begin{pmatrix} 3\\ -3\\ -4 \end{pmatrix}
=\lambda \begin{pmatrix} 3\\ -3\\ -4 \end{pmatrix}$

выполним перемножение матриц

$\begin{pmatrix} 0*3 + 3*-3 + 0*-4\\ 3*3+0*-3+0*-4\\ 0*3+0*-3 + 3*-4 \end{pmatrix}$

$\begin{pmatrix} -9\\ 9\\ -12 \end{pmatrix}$

$\begin{cases}
-9= 3\lambda \\
9= -3\lambda \\
-12= -4\lambda
\end{cases}$

$\begin{cases}
\lambda = -3\\
\lambda = -3 \\
\lambda = 3
\end{cases}$

вывод: не являеться

In [4]:
a = np.array([[0,3,0],[3,0,0],[0,0,3]])
b = np.array([[3],[-3],[-4]])
np.dot(a,b)

array([[ -9],
       [  9],
       [-12]])